from app.models.administracao import Administracao
from app.models.consulta import Consulta
from app.models.profissionalSaude import ProfissionalSaude
from app.models.internacao import Internacao
from app.models.paciente import Paciente
from app.models.receita import Receita
from app.models.telemedicina import Telemedicina
from app.models.leito import Leito
from app.models.profissionalInternacao import ProfissionalInternacao
from app.models.usuario import Usuario